// BurgerBuilder
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const INIT_INGREDIENT = 'INIT_INGREDIENT';
export const FETCH_INGREDIENT_FAILED = 'FETCH_INGREDIENT_FAILED';

// Order
export const BURGER_PURCHASE_START = 'BURGER_PURCHASE_START';
export const BURGER_PURCHASE_SUCCESS = 'BURGER_PURCHASE_SUCCESS';
export const BURGER_PURCHASE_FAIL = 'BURGER_PURCHASE_FAIL';
export const BURGER_PURCHASE_ONINIT = 'BURGER_PURCHASE_ONINIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

